on:
  workflow_dispatch: {}
  

jobs:
  find-jobs:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo '::set-output name=o1::{"path": ["1-a", "1-b"]}'
          echo '::set-output name=o2::{"path": ["2-a"]}'
          echo '::set-output name=o3::{"path": []}'
    outputs:
      o1: ${{ steps.step1.outputs.o1 }}
      o2: ${{ steps.step1.outputs.o2 }}
      o3: ${{ steps.step1.outputs.o3 }}

  _1:
    if: fromJSON(needs.orchestrator.outputs.o1).path[0] != null
    runs-on: ubuntu-latest
    needs: find-jobs
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.o1) }}
    steps:
      - run: echo ${{ matrix.path }}
      - if: matrix.path == '1-b'
        run: echo 'Step exclusive for 1-b'

  _2:
    if: fromJSON(needs.orchestrator.outputs.o2).path[0] != null
    runs-on: ubuntu-latest
    needs: [find-jobs, _1]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.o2) }}
    steps:
      - run: echo ${{ matrix.path }}

  _3:
    if: fromJSON(needs.orchestrator.outputs.o3).path[0] != null
    runs-on: ubuntu-latest
    needs: [find-jobs, _1, _2]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.o3) }}
    steps:
      - run: echo ${{ matrix.path }}
