on:
  workflow_dispatch: {}

jobs:
  orchestrator:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo '::set-output name=json::{"order1": ["one111", "two222"], "order2": ["zzz-mmm"], "order3": ["xxx-yyy"]}'
    outputs:
      matrix: ${{ steps.step1.outputs.json }}

  order1jobs:
    runs-on: ubuntu-latest
    needs: orchestrator
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.order1 }}

  order2jobs:
    runs-on: ubuntu-latest
    needs: [orchestrator, order1jobs]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.order2 }}

  order3jobs:
    runs-on: ubuntu-latest
    needs: [orchestrator, order1jobs, order2jobs]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.order3 }}
