on:
  workflow_dispatch: {}

jobs:
  orchestrator:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo '::set-output name=order1::{"jobname": ["1-a", "1-b"]}'
          echo '::set-output name=order2::{"jobname": ["2-a"]}'
          echo '::set-output name=order3::{"jobname": []}'
    outputs:
      matrix1: ${{ steps.step1.outputs.order1 }}
      matrix2: ${{ steps.step1.outputs.order2 }}
      matrix3: ${{ steps.step1.outputs.order3 }}

  _1:
    if: fromJSON(needs.orchestrator.outputs.matrix1).jobname[0] != null
    runs-on: ubuntu-latest
    needs: orchestrator
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix1) }}
    steps:
      - run: echo ${{ matrix.jobname }}
      - if: matrix.jobname == '1-b'
        run: echo 'Step exclusive for 1-b'

  _2:
    if: fromJSON(needs.orchestrator.outputs.matrix2).jobname[0] != null
    runs-on: ubuntu-latest
    needs: [orchestrator, _1]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix2) }}
    steps:
      - run: echo ${{ matrix.jobname }}

  _3:
    if: fromJSON(needs.orchestrator.outputs.matrix3).jobname[0] != null
    runs-on: ubuntu-latest
    needs: [orchestrator, _1, _2]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix3) }}
    steps:
      - run: echo ${{ matrix.jobname }}
