on:
  workflow_dispatch: {}

jobs:
  orchestrator:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo '::set-output name=order1::{"job": [{"path": "1-a", "deploy": true, "steps": [{"run": "echo ${{ matrix.job.path }}"},{"if": "matrix.job.deploy == true","run": "echo 'Deploying ${{ matrix.job.path }}'"}]}]}'
          echo '::set-output name=order2::{"job": [{"path": "2-a", "deploy": true}]}'
          echo '::set-output name=order3::{"job": []}'
    outputs:
      matrix1: ${{ steps.step1.outputs.order1 }}
      matrix2: ${{ steps.step1.outputs.order2 }}
      matrix3: ${{ steps.step1.outputs.order3 }}

  _1:
    if: fromJSON(needs.orchestrator.outputs.matrix1).job[0] != null
    runs-on: ubuntu-latest
    needs: orchestrator
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix1) }}
    steps: ${{ matrix.steps }}

  _2:
    if: fromJSON(needs.orchestrator.outputs.matrix2).job[0] != null
    runs-on: ubuntu-latest
    needs: [orchestrator, _1]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix2) }}
    steps:
      - run: echo ${{ matrix.job.path }}
      - if: matrix.job.deploy == true
        run: echo 'Deploying ${{ matrix.job.path }}'

  _3:
    if: fromJSON(needs.orchestrator.outputs.matrix3).job[0] != null
    runs-on: ubuntu-latest
    needs: [orchestrator, _1, _2]
    strategy:
      matrix: ${{ fromJSON(needs.orchestrator.outputs.matrix3) }}
    steps:
      - run: echo ${{ matrix.job.path }}
      - if: matrix.job.deploy == true
        run: echo 'Deploying ${{ matrix.job.path }}'
