on:
  workflow_dispatch: {}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo '::set-output name=test-json::{"job": ["one111", "two222"]}'
    outputs:
      matrix: ${{ steps.step1.outputs.test-json }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.job }}
