name: Reusable workflow example greeter

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        
jobs:
  greet:
    name: Greet user
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hi, ${{ inputs.username }}! 🙌"
