# This is a basic workflow to help you get started with Actions

name: reusable caller

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: World

jobs:
 
  call-reusable-workflow:
    uses: ilyasotkov/gha-playground/.github/workflows/reusable-workflow.yml@main
    with:
      username: ${{ github.event.inputs.name }}
      
